# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2E5OTBhOTdlYTg0ZDRmODAzNmE5ZmJlZDg0MjNjZjQ0MGY4ZDUwZTA2MGJiMzFhMDM4ZjUxYTM5ZWE0ZjBhZDk1OGM0ZWU0NjQ5YzhlOTkwMzJkYjIwYjAwZWI1Y2M1MGE1YzUzZGExZjcwZTRiYzU2NGJhMThhNjVmYjhmNjk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
